# Wrangler configuration for Cloudflare Workers deployment

name = "galaxy-sim"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

# Main worker script (optional - for static sites we mainly use assets)
main = "worker.js"

# Static assets configuration
[assets]
directory = "./pkg"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

# Environment variables (if needed)
[vars]
ENVIRONMENT = "production"

# Custom routing (if needed for API endpoints)
[[routes]]
pattern = "galacto.tre.systems/*"
zone_name = "tre.systems"         # Your domain

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = ["src", "static"]

# Development configuration
[dev]
port = 8787
local_protocol = "https"
upstream_protocol = "https"
